version: '3.8'

services:
  # Бэкенд (CakePHP)
  api:
    build: ./backend
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=currency
      - REDIS_HOST=redis
      - COMPOSER_ALLOW_SUPERUSER=1
  scheduler:
    image: alpine:3.18
    command: >
      sh -c "echo '*/5 * * * * /usr/bin/wget -qO- http://api/currency_fetch' > /etc/crontabs/root && crond -f"
    depends_on:
      - api

  # База данных MySQL
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: currency
    volumes:
      - mysql_data:/var/lib/mysql

  # Redis для кэширования
  redis:
    image: redis:alpine

  # Фронтенд (React)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true

volumes:
  mysql_data: